spring:
  datasource:
    url: jdbc:mysql://localhost:3306/map_service
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: task_list



